---
title: "Estadística Inferencial" 
author:   
  - Jackson M'coy Romero Plasencia 
institute:   
  -  \large Universidad Nacional de San Cristóbal de Huamanga   
  -  \normalsize Departamento Académico de Matemática y Física 
date: Ayacucho 2020 
output:   
  beamer_presentation:  
    incremental: false  
    theme: "Marburg"  
    colortheme: "default"
    fonttheme: "structurebold"  
    toc: true   
    slide_level: 3
    keep_tex: true
header-includes: 
- \usepackage{ragged2e}
- \usepackage{color}
- \usepackage{listings}
- \usepackage{multicol}
- \AtBeginSubsection{}   
---

$$\begin{matrix}
 x&  =& 0\quad\quad 1\quad\quad 2\quad\quad 3\quad\quad 4 \\ 
 f_X(x)&=&4/12\quad 4/12\quad 2/12\quad 1/12\quad 1/12 \\ 
 &  & 
\end{matrix}
$$

```{r}
x<-0:4
fx<-c(4/12,4/12,2/12,1/12,4/12)
media<-x*fx
```



$$\mathbb{E}(X^2)=0+4/12+8/12+9/12+16/12=37/12$$


$$\mathbb{E}(X)=0+4/12+4/12+3/12+4/12=15/12$$




$$Z=\displaystyle \frac{\overline{X}-\mu}{\sigma/\sqrt{n} } $$

```{r}
mepob<-6
varpob<-36
n=9
curve(dnorm(x,mepob,sqrt(varpob/n)),-2,14,lwd=2, col='red',
      xlab='',ylab='',axes=F )
axis(1,lwd=2)
abline(v=mepob, lty=2)
x2<-seq(2,14,l=100)
polygon(c(2,x2,14),c(0,dnorm(x2,mepob,sqrt(varpob/n)),0),col='blue', density = 20, angle=45)
text(6,0.08,0.985)

```

```{r}
k=qnorm(0.015,6,2)
k
```

$$P(\overline{X}>c)=0.985$$
$$1- P(\overline{X}\leq c)=0.985$$
$$P(\overline{X}\leq c)=0.015$$
$$P\bigg(\displaystyle \frac{\overline{X}-\mu}{\sigma/\sqrt{n}} \leq \displaystyle \frac{c-6}{6/\sqrt(3)}\bigg)=0.015$$
$$P\bigg(Z \leq \displaystyle \frac{c-6}{6/3}\bigg)=0.015$$
```{r}
qnorm(0.015)
```

$$P(Z<-2.17)=0.015$$
$$\frac{c-6}{2}=-2.17 $$
```{r}
k=2*(-2.17)+6
k
```
poblacion tiene distribución de Poisson
n=10

$$X\longrightarrow P(\lambda)$$
$$\mathbb{E}(X)=\mathbb{V}(X)=\lambda $$
$$\displaystyle \frac{e^{-\lambda}\,x^\lambda}{x!}\quad x=0,1,... $$
$$Z=\displaystyle\frac{\overline{X}-\mu }{\sigma/\sqrt{n}} $$
$$Z=\displaystyle\frac{\overline{X}-\lambda }{\sqrt\lambda{} /\sqrt{n}} $$


$$X\longrightarrow Bin(n,p)$$

$$\mathbb{E}(X)=np \quad\mathbb{V}(X)=np(1-p)$$

$$Z=\displaystyle\frac{\overline{X}-\mu }{\sigma/\sqrt{n}} $$

$$Z=\displaystyle\frac{\overline{X}-np }{\sqrt{np(1-p)} /\sqrt{n}} $$

X tenga distribución de probabilidad exponencial(1/2)

$$\mathbb{E}(X)=2 \quad \mathbb{V}(X)=4 $$


$$Z=\displaystyle\frac{\overline{X}-2 }{\sqrt{4} /\sqrt{n}} $$




X tenga distribución de probabilidad Gamma(alfa, beta)

$$\mathbb{E}(X)=\alpha\beta \quad \mathbb{V}(X)=\alpha\beta^2 $$


$$Z=\displaystyle\frac{\overline{X}-\alpha\beta }{\sqrt{\alpha\beta^2} /\sqrt{n}} $$

$$Z=\displaystyle\frac{\overline{X}-p }{\sqrt{p(1-p)} /\sqrt{n}} $$

Y=3X-5

$$\mathbb{E}(Y)=\mathbb{E}(3X-5)$$
$$\mathbb{E}(Y)=3\mathbb{E}(X)-5$$
$$\overline{Y}=3\overline{X} -5$$
$$P(\overline{Y}>28)=P(3\overline{X} -5>28)$$
$$P(\overline{Y}>28)=P(\overline{X}>11)$$
xbar tiene distribución norma $N(6,4)$
```{r}
xbar<-rnorm(1e5,6,2)
sum(xbar>11)/1e5
```

$$P(\overline{X}> 11)=1-P(X\leq 11) $$

$$1-P\bigg(\displaystyle \frac{\overline{X}-\mu}{\sigma/\sqrt{n}} \leq \displaystyle \frac{11-6}{2}\bigg)=1-P(Z\leq 2.5) $$



```{r}
1-pnorm(2.5)
round(1-pnorm(2.5),4)
```


# Ejercicio 8
###Simulación montecarlo

```{r}
f<-function(x){
  f1<-ifelse(x>=0 & x<=1,2-2*x,0)
  return(f1)}
x<-seq(-1,2,l=100)  
plot(x,f(x), lwd=2,type='l', col='red')  
```
```{r}
f.mc<-function(n,a,b){
  x<-runif(n,a,b)
  f2<-(b-a)*mean(f(x))
  return(f2)
}
f.mc(1e6,0,1)

```

Media: $\mathbb{E}(X)$
```{r}
E.mc<-function(n,a,b){
  x<-runif(n,a,b)
  f2<-(b-a)*mean(f(x)*x)
  return(f2)
}
E.mc(1e6,0,1)

```

$$\mathbb{E}(X)= \int_{0}^{1}x(2-2x)dx=\int_{0}^{1}(2x-2x^2)dx=\Bigg|_{0}^{1}x^2-2\frac{x^3}{3}=1-2/3=1/3=\mu $$
```{r}
1/3
```

Varianza: $\mathbb{V}(X)$
```{r}
V.mc<-function(n,a,b){
  x<-runif(n,a,b)
  f2<-(b-a)*((mean(f(x)*x^2))-(mean(f(x)*x)^2))
  return(f2)
}
V.mc(1e6,0,1)
```

$$\mathbb{E}(X^2)= \int_{0}^{1}x^2(2-2x)dx=\int_{0}^{1}(2x2-2x^3)dx=\Bigg|_{0}^{1}2\frac{x^3}{3}-\frac{x^4}{2}=2/3-1/2=1/6 $$

$$\mathbb{V}(X)=\mathbb{E}(X^2)-\mathbb{E}(X)^2=1/6-1/9=1/18=\sigma^2$$
```{r}
1/18
```

$$P(3580<\overline{X}<3620)$$
$$P(3580<\overline{X}<3620)=P(|\overline{X}-\mu|< 20)=$$
$$P(|\overline{X}-\mu|< 20)=P(-20<\overline{X}-3600< 1*(20)) $$
$$P(a<x<b)=P(a<x\leq b)=P(a\leq x< b)=P(a\leq x\leq b)$$
$$P(3580<\overline{X}<3620)=P(|\overline{X}-\mu|< 1*(20))=$$

$$P\bigg(\displaystyle \frac{3580-3600}{20} < \frac{\overline{X}-\mu}{\sigma/\sqrt{n}} <\frac{3620-3600}{20}\bigg)=P( -1<z<1) $$



$$\overline{Y}= \mathbb{E}(Y)=\mathbb{E}(0.2X+100) $$

$$\overline{Y}= \mathbb{E}(Y)=0.2\mathbb{E}(X)+100=0.2\overline{X}+100 $$

$$\overline{Y}=0.2\overline{X}+100 $$
$$P(\overline{Y}>7541)=P(0.2\overline{X}+100>7541)$$
$$P(\overline{Y}>7541)=P(\overline{X}>37205)$$
$$P(\overline{Y}>7541)=P\bigg(\displaystyle \frac{\overline{X} -\mu}{\sigma/\sqrt{n}} >\frac{37205 -38000}{3000/\sqrt{n}}\bigg)$$
$$P\bigg(Z >\frac{37205 -38000}{3000/\sqrt{n}}\bigg)=0.996$$
(37205-38000)/3000

$$P(Z >-0.265\sqrt{n} )=0.996$$


$$P(Z >-2.65)=0.996$$
```{r}
qnorm(0.996, lower.tail = F)

```

$$-2.65=-0.265\sqrt{n}$$
n=(2.65/0.265)^2
n

$$P(165\leq X\leq 235)=P(|X-200|\leq 35)=2P(X-200\leq 35)-1=0.9876$$

(0.9876+1)/2

$$P(165\leq X\leq 235)=P(|X-200|\leq 35)=P(|X-\mu|\leq 35)=0.9938$$

$$P(165\leq X\leq 235)=P(|X-200|\leq 35)=P((X-\mu)/\sigma\leq 35/\sigma)=0.9938$$
$$P(165\leq X\leq 235)=P(|X-200|\leq 35)=P(Z\leq 35/\sigma)=0.9938$$


```{r}
qnorm(0.9938)
```
$$2.5=35/\sigma$$

```{r}
s=35/2.5
s
```

$$P(\overline{X}<205)=P(Z<(205-200)/14/\sqrt{n}) =0.9938$$

$$P(\overline{X}<205)=P(Z<(0.357\sqrt{n})) =0.9938$$

```{r}
qnorm(0.9938)
```
$$2.5=0.357\sqrt{n} $$
```{r}
n<-(2.5/0.357)^2
n
```

#################################

$$X \longrightarrow Exp(1000=\lambda, 1000^2=\lambda^2)$$
$$Z= \displaystyle \frac{\overline{X}-\mu }{\sigma/\sqrt{n}} $$
800 y 1200 = 0.9544
200
$$P(|\overline{X}-\mu|\leq 200 )=0.9544$$

$$P(|Z|\leq 200/1000\sqrt{n} )=0.9544$$
$$2P(Z\leq 0.2\sqrt{n})-1=0.9544$$
$$P(Z\leq 0.2\sqrt{n})=0.9772$$
n=(2/0.2)^2
n

