---
title: "Estadística Inferencial" 
author:   
  - Jackson M'coy Romero Plasencia 
institute:   
  -  \large Universidad Nacional de San Cristóbal de Huamanga   
  -  \normalsize Departamento Académico de Matemática y Física 
date: Ayacucho 2020 
output:   
  beamer_presentation:  
    incremental: false  
    theme: "Marburg"  
    colortheme: "default"
    fonttheme: "structurebold"  
    toc: true   
    slide_level: 3
    keep_tex: true
header-includes: 
- \usepackage{ragged2e}
- \usepackage{color}
- \usepackage{listings}
- \usepackage{multicol}
- \AtBeginSubsection{}   

---


## Ejercicio 1

\justifying   La distribución de las notas del examen final de Mat. I resultó ser normal $N(\mu,\sigma^2)$, con cuartiles 1 y 3 iguales a 6.99 y 11.01 respectivamente.
\begin{itemize}\justifying 
  \item [a.] Determine la media y la varianza de la distribución de las notas.
  \item [b.] Halle el intervalo $[a,b] $ centrado en $\mu$ tal que $P( a\leq\overline{X} \leq b)=0.9544$, donde $\overline{X}$ es la media de la muestra $X_1,X_2,X_3, X_4$ escogida de esa población 
\end{itemize}


## Ejercicio 2
\justifying Un proceso automático llena bolsas de café cuyo peso neto tiene una media de 250 gramos y un desviación estándar de 3 gramos. Para controlar el proceso, cada hora se pesan 36 bolsas escogidas al azar; si el peso neto medio está entre 249 y 251 gramos se continúa con el proceso aceptando que el peso neto medio es 250 gramos y en caso contrario, se detiene el proceso para reajustar la máquina.

\begin{itemize}\justifying 
  \item [a.] ¿Cuál es la probabilidad de detener el proceso cuando el peso neto medio realmente es 250 ?
  \item [b.] ¿Cuál es la probabilidad de aceptar que el peso neto promedio es 250 cuando realmente es de 248 gramos ? 
\end{itemize}


## Ejercicio 3

La duración en horas de una marca de tarjeta electrónica se distribuye exponencialmente con promedio de 1000 horas.
\begin{itemize}\justifying 
  \item [a.] Halle el tamaño $n$ de la muestra de manera que sea 0.9544 la probabilidad de que su media muestral esté entre 800 y 1200 horas.
  \item [b.] Si se obtiene una muestra aleatoria de 100 de esas tarjetas calcular la proabilidad que la duración media de la muestra sea superior a 1100 horas.
\end{itemize}

## Distribución Exponencial

$$f_X(x,\lambda)=f_X(x)= \frac{\displaystyle e^{\,-x/\lambda} }{\lambda} \quad x\geq0$$ 
Hallando el $\mathbb{E}(X)$ y $\mathbb{V}(X)$. Para trabajar con integrales, definidas en $x\geq 0$, vamos a utilizar la functión gamma 
$$ \Gamma(\alpha)=\displaystyle\int_{0}^{\infty}\, y^{\alpha-1}\,\displaystyle e^{-y}\,dy =(\alpha-1)!$$


$$\mathbb{E}(X)  = \displaystyle\int_{0}^{\infty}x\, \frac{\displaystyle e^{\,-x/\lambda} }{\lambda}\,dx  = \displaystyle\int_{0}^{\infty} \bigg(\frac{x}{\lambda}\bigg) \, \displaystyle e^{\,-(x /\lambda)} \,dx$$


$$\mathbb{E}(X)  = \displaystyle\int_{0}^{\infty}x\, \frac{\displaystyle e^{\,-x/\lambda} }{\lambda}\,dx =\lambda\displaystyle\int_{0}^{\infty} \bigg(\frac{x}{\lambda}\bigg)^{\color{red}2-1 } \, \displaystyle e^{\,-(x /\lambda)} \,d(x/\lambda)$$

$$\mathbb{E}(X)  =\lambda\Gamma(2)=\lambda(2-1)!=\lambda $$

##


$$\mathbb{E}(X^2)  = \displaystyle\int_{0}^{\infty}x^2\, \frac{\displaystyle e^{\,-x^/\lambda} }{\lambda}\,dx  = \displaystyle\int_{0}^{\infty} \bigg(\frac{x^2}{\lambda}\bigg) \, \displaystyle e^{\,-(x /\lambda)} \,dx$$


$$\mathbb{E}(X^2)  = \displaystyle\int_{0}^{\infty}x\, \frac{\displaystyle e^{\,-x/\lambda} }{\lambda}\,dx =\lambda^2\displaystyle\int_{0}^{\infty} \bigg(\frac{x}{\lambda}\bigg)^{\color{red}3-1 } \, \displaystyle e^{\,-(x /\lambda)} \,d(x/\lambda)$$

$$\mathbb{E}(X^2)  =\lambda^2\Gamma(3)=\lambda(3-1)!=2\lambda^2 $$
$$\mathbb{V}(X)=\mathbb{E}(X^2)-(\mathbb{E}(X))^2 =2\lambda^2- \lambda^2=\lambda^2$$


## Solución

Ejercicio 1.




## Ejercicio 2
a. \justifying 
$$P(\overline{X}<249|\mu=250)=P\Bigg(\frac{\overline{X}-\mu}{\sigma/\sqrt{n}} <\frac{ 249-250}{3/6}\Bigg) $$
$$P(\overline{X}<249|\mu=250)=P(Z<-2)=0.02275$$



Probabilidad de detener el proceso es:2(0.02275)=  0.04550026

b.\justifying 
$$P(\overline{X}>249|\mu=248)=P\Bigg(\frac{\overline{X}-\mu}{\sigma/\sqrt{n}} >\frac{ 249-248}{3/6}\Bigg) $$
$$P(\overline{X}>249|\mu=248)=P(Z>2)=P(Z<-2)=0.02275$$

Probabilidad de detener el proceso es:0.02275






